### ISSUE TITLE
Remove Cairo

### ISSUE THREAD

**Issue by ai** [jonathantneal/postcss-conic-gradient#10]
We should think how to do the same without Cairo

**Comment by jonathantneal** [comment]
I agree. Unfortunately, this issue may not help anyone if no one knows how to do this or can contribute an alternative.

**Comment by ai** [comment]
@jonathantneal I made this issue to have a link from our Cult of Martians

**Comment by khovansky-al** [comment]
@jonathantneal @ai Hello everyone. Saw this issue on the Cult website and spent this weekend working on it. I achieved some results but now I need your input here.

I initially went with `node-pureimage` library but it quickly became clear that it just won't cut it. Their implementation is way different with what browsers have to offer, unfortunately. Generated images were simply incorrect no matter how hard you try. 

There is though a library named Skia which seems to be used under the hood in Chrome and they are currently working on an official WASM version of the library (thanks to inspiration from @Zubnix who initially ported a subset of the lib).

I found 2 modules they have: `PathKit` and `CanvasKit` and implemented a solution using both of them. But before I make a PR we should choose one. So here's the deal.
### PathKit
Pros:
+ Has a published npm module, so can be easily used as a dependency
+ Is somewhat documented and left the *experimental* stage a while ago

Cons:
+ Not a canvas replacement, can only generate SVG path commands in node.
+ The resulting SVG is HUGE! The 400x400 hue wheel svg is almost a 100KB. I am not sure if that is an issue since the original @LeaVerou polyfill generated SVG was about 80KB but it feels like a lot for a single declaration. Will it be fine if there are lots of them?

### CanvasKit
Pros:
+ Is a fully featured drop-in replacement for canvas
+ From p1 -> can generate a real image and after some changes to bindings even with a format selection: PNG or JPEG
+ 400x400 PNG is 50KB, JPEG with 50 quality argument is 6KB

Cons:
+ Experimental thing, literally resides under `experiments` folder, doesn't have an npm module
+ Required some manual changes to make it work for us

Now, the CanvasKit is really cool but I had to make changes to the Emscripten bindings - the `arc` function wasn't exposed and the exposed overload for `encodeToData` was the one without parameters. After switching the overload I was able to render JPEG with a quality parameter and finally got the hue wheel as a 6KB picture, although with visible compression artefacts. You can take a look yourself: https://codepen.io/alx-khovansky/pen/rQMQXN (this is a pasted output from the plugin)
We can add a format & quality option to the plugin though so that people can decide for themselves what is more important.

So, for now the CanvasKit seems like the best option. But it implies that we have to maintain a fork with changes we need + precompile JS/WASM and ship it along with the plugin until they release a public version. 

What do you think?

P.S. If none of the proposals seem good enough I can release it as a separate plugin.

**Comment by khovansky-al** [comment]
@jonathantneal I had this thought too but after researching there doesn't seem to exist anything lightweight and capable enough. Mainly because to transform this you have to implement an arraybuffer-like canvas mock and all the graphics related things and we are back to square one.
`svg-to-img` mentions on their npm page:

> Note: When you install svg-to-img, it downloads a recent version of Chromium (~170Mb Mac, ~282Mb Linux, ~280Mb Win) that is guaranteed to work with the library.

Having to download so much for a simple transformation kind of defeats the purpose.
Plus, again from the description:

> If you're planning on running svg-to-img on Debian, you will need to manually install the following dependencies: \<a huge list of dependencies\>

We will add even more dependency headache for people who build their frontend on CI/CD.

**Comment by ai** [comment]
I think CanvasKit is a good option.

1. Ask CanvasKit to release it.
2. If they will not release it on npm, put in git repository as git submodule and take it to our npm package

**Comment by khovansky-al** [comment]
Ok. I will have to talk to people who work on Skia and try to submit a patch with our required changes there first.
I'll keep you updated.

**Comment by khovansky-al** [comment]
Alright, landed the changes to Skia master. Kudos to @kjlubick for an instant review! As he said, npm module is on the roadmap but not ready just yet.
I will work on incorporating canvaskit as a submodule for now. We can switch to a proper npm lib as soon as it releases.

**Comment by jonathantneal** [comment]
So, can we make the move?

**Comment by khovansky-al** [comment]
@jonathantneal Yes. I'm sorry, had a lot going on lately. I will make the PR with canvaskit on the coming weekend.

**Comment by khovansky-al** [comment]
@jonathantneal PR got delayed but it's finally here. Would love to hear your thoughts on it: #11. Very sleepy but hopefully the description is readable 😄 

I think that we might think about a ground-up rewrite (1.0) to address some things:
- There is an updated polyfill algorithm available now. I initially implemented changes into the PR but decided to ditch them as unrelated
- We now mix things from 2 worlds: old node and new one. Async/await alongside with plain old `var`. Can upgrade the codebase
- We now have options that can be implemented. Not only width/height but also image format and quality for JPEG
- Things can be separated into modules for increased readability and maintainability
- Not only readability, but for the sake of testability. Currently we have a sanity test that compares a huge pre-existing base64 string. I feel like we can check plugin sanity with a small 1x1 generated image and check plugin correctness by comparing a set of images pre-generated with a browser and our output using something like https://github.com/mapbox/pixelmatch. To do that we have to extract code that generates the image.

If that is something that you think would benefit the plugin then I'd love to work on those proposals after we finish with the originally planned transition.

**Comment by jonathantneal** [comment]
@khovansky-al, I have moved the updated plugin to https://github.com/jonathantneal/postcss-conic-gradient/tree/next

I hope this will encourage you, as we can now use modern JavaScript to write the plugin. I’ve only started by addressing some of the concerns you mentioned with the old PostCSS syntax, and by breaking out the unique functions (one looks more like a class) into their own files.
